### ISSUE TITLE
Please add a MVC sample.

### ISSUE THREAD

**Issue by lbgitjp** [edgesharp/EdgeSharp.Samples#1]
There is a chromely MVC sample, https://github.com/chromelyapps/demo-projects/tree/master/web-chromely/web-chromely-mvc,
I hope you can add a EdgeSharp MVC sample,
Thanks！

**Comment by mattkol** [comment]
@lbgitjp chromely MVC sample was actually a contribution that we continue to maintain. It is difficult to satisfy most requirements, so easier to stay with the basics. Unless there is a contribution towards this, I cannot make that promise yet. Thanks.
